fix: InitialRead will refetch data to capture schema + layout (#1787)
Part of #1749, fixes the first issue

> Cannot read from vortex file, and error msg is

>    table = vx.io.read_path("A0.vortex")
>ValueError: Schema, layout, & footer must be in the initial read, got
schema at 1889911040 and initial read from 1903721816

> accroding to this
[img](https://spiraldb.github.io/vortex/docs/_images/file-format-2024-10-23-1642.svg),
footer is too large? the table has 14k+ columns, which is very wide.